
--select * from customer

--Q1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied ='Yes' and purchase_amount >=(SELECT AVG(purchase_amount) FROM customer);

--Q3. what are the top 5 products with highest average review rating
SELECT item_purchased, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

--Q4.Compare the average purchase amounts between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

--Q5.Do subscribed custome
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount), 2) AS avg_spend,
ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status;